const updatePill=document.getElementById('update-pill'),updateText=document.getElementById('update-text'),updateAction=document.getElementById('update-action');
const message=document.getElementById('message'),pageTitle=document.getElementById('page-title'),documentsSettings=document.getElementById('documents-settings'),documentsStatus=document.getElementById('documents-status'),documentsStatusText=document.getElementById('documents-status-text'),documentsUrl=document.getElementById('documents-url'),saveDocumentsUrl=document.getElementById('save-documents-url'),editDocumentsUrl=document.getElementById('edit-documents-url');
let currentPage='vaccine',documentsReady=false,editingDocuments=false;
function renderDocumentsControls(){const onDoc=currentPage==='documents-local';documentsStatus.hidden=!onDoc||!documentsReady||editingDocuments;documentsSettings.hidden=!onDoc||(documentsReady&&!editingDocuments);if(documentsReady)documentsStatusText.textContent='● DOC เชื่อมต่อแล้ว'}
function setModuleStatus(name,status){const ready=Boolean(status?.ready);if(name==='documents-local')documentsReady=ready;document.querySelectorAll(`[data-page="${name}"]`).forEach(button=>{if(name==='documents-local'){button.disabled=false;button.classList.toggle('offline',!ready);button.title=ready?'ระบบ DOC พร้อมใช้งาน':'กดเพื่อตั้งค่าที่อยู่ระบบ DOC';}else{button.disabled=!ready;}});renderDocumentsControls()}
async function refreshStatus(){try{const statuses=await window.homeHospital.status();setModuleStatus('vaccine',statuses.vaccine);setModuleStatus('ua-online',statuses['ua-online']);setModuleStatus('documents-local',statuses['documents-local']);return statuses}catch(error){console.error(error);message.textContent='ตรวจสอบสถานะระบบไม่สำเร็จ';return null}}
function markActive(name){currentPage=name;document.querySelectorAll('.nav-item').forEach(item=>item.classList.toggle('active',item.dataset.page===name));renderDocumentsControls()}
async function navigate(name){try{const titles={vaccine:'ระบบวัคซีน','ua-online':'UA Report','documents-local':'บัตรนัด / ใบเสร็จ'};pageTitle.textContent=titles[name]||'ระบบงาน';markActive(name);if(name==='documents-local'){const statuses=await refreshStatus();if(!statuses?.['documents-local']?.ready){editingDocuments=true;renderDocumentsControls();message.textContent='ระบบ DOC ยังเชื่อมต่อไม่ได้ — ตั้งค่า URL/IP เครื่องแม่ทางแถบซ้ายแล้วกดบันทึก';return;}editingDocuments=false;renderDocumentsControls()}message.textContent=`กำลังโหลด ${pageTitle.textContent}...`;const result=await window.homeHospital.navigate(name);message.textContent=result.message;if(name==='documents-local')refreshStatus()}catch(error){console.error(error);message.textContent='เปิดระบบไม่สำเร็จ'}}
async function loadDocumentsUrl(){try{const result=await window.homeHospital.getDocumentsUrl();if(result?.url)documentsUrl.value=result.url}catch(error){console.error(error)}}
editDocumentsUrl.addEventListener('click',()=>{editingDocuments=true;renderDocumentsControls();documentsUrl.focus();message.textContent='แก้ไขที่อยู่ระบบ DOC แล้วกดบันทึก'});
saveDocumentsUrl.addEventListener('click',async()=>{saveDocumentsUrl.disabled=true;try{const result=await window.homeHospital.setDocumentsUrl(documentsUrl.value.trim());message.textContent=result.message;if(result.ok){documentsUrl.value=result.url;const statuses=await refreshStatus();if(statuses?.['documents-local']?.ready){editingDocuments=false;renderDocumentsControls();message.textContent='เชื่อมต่อระบบ DOC สำเร็จ';}else{editingDocuments=true;renderDocumentsControls();message.textContent='บันทึกแล้ว แต่ยังเชื่อมต่อระบบ DOC ไม่ได้ กรุณาตรวจ IP/พอร์ตและเครื่องแม่';}}}catch(error){console.error(error);message.textContent='บันทึกที่อยู่ระบบไม่สำเร็จ'}finally{saveDocumentsUrl.disabled=false}});
document.querySelectorAll('[data-page]').forEach(button=>button.addEventListener('click',()=>navigate(button.dataset.page)));
(async()=>{await loadDocumentsUrl();const statuses=await refreshStatus();if(statuses?.vaccine?.ready){await navigate('vaccine');return}const fallback=['ua-online','documents-local'].find(name=>statuses?.[name]?.ready);if(fallback)await navigate(fallback);else message.textContent='ยังไม่มีระบบที่พร้อมใช้งาน'})();

function renderUpdateState(state={}){if(!updatePill)return;updatePill.classList.remove('downloading','ready','error');if(['available','downloading'].includes(state.status))updatePill.classList.add('downloading');if(state.status==='ready')updatePill.classList.add('ready');if(state.status==='error')updatePill.classList.add('error');updateText.textContent=state.status==='downloading'?`อัปเดต ${state.percent||0}%`:state.status==='ready'?`พร้อม v${state.availableVersion}`:`v${state.version||'0.1.0'}`;updateAction.disabled=['checking','available','downloading'].includes(state.status);updateAction.textContent=state.status==='ready'?'ติดตั้ง':'ตรวจอัปเดต';updatePill.title=state.message||'ระบบอัปเดตอัตโนมัติ'}
updateAction?.addEventListener('click',async()=>{try{const state=await window.homeHospital.getUpdateState();if(state.status==='ready'){message.textContent='กำลังรีสตาร์ตเพื่อติดตั้งอัปเดต...';await window.homeHospital.installUpdate();return}message.textContent='กำลังตรวจสอบอัปเดต...';await window.homeHospital.checkForUpdates()}catch(error){console.error(error);message.textContent='ตรวจสอบอัปเดตไม่สำเร็จ'}});
window.homeHospital.onUpdateState(state=>{renderUpdateState(state);if(state?.message)message.textContent=state.message;if(state?.status==='error'&&state?.errorDetail){updatePill.title=state.errorDetail;console.error('Auto Update:',state.errorDetail)}});
window.homeHospital.getUpdateState().then(renderUpdateState).catch(console.error);
